### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by marktsuchida** [PicoQuant/PicoQuant-Time-Tagged-File-Format-Demos#3]
https://github.com/PicoQuant/PicoQuant-Time-Tagged-File-Format-Demos/blob/4a27c853ffb462e6c689dd6881c60a23ad3f51aa/doc/apx_tttrrecords.html#L187-L188

I suspect line 188 should read "PicoHarp 330".

**Comment by snizzleorg** [comment]
Thanks. I fixed the typo
